### ISSUE TITLE
Syntax check does not include vhosts

### ISSUE THREAD

**Issue by JBlond** [enderandpeter/win-a2enmod#2]
the -t parameter does not check the vhosts. -S might be the better choise

**Comment by enderandpeter** [comment]
Hey, thanks a lot for your feedback. I was meaning to provide a way to see which sites are enabled and available. The `httpd -t` command is meant to check the syntax of the conf file(s) to make sure the server will actually restart after the changes to the main or included configurations.

From what I can tell, the only meaningful info about vhosts returned by `httpd -S` is the first part of that output, which is also returned by `httpd -D DUMP_VHOSTS`. I have a site enabled in the file wps.conf and that latter command shows me the following:

```
*:80                   is a NameVirtualHost
     default server localhost (C:/Apache24/conf/sites-enabled/wps.conf:32)
     port 80 namevhost localhost (C:/Apache24/conf/sites-enabled/wps.conf:32)
     port 80 namevhost localhost (C:/Apache24/conf/sites-enabled/wps.conf:32)
```

I'm not sure why it lists the site configuration file three times, but it looks like the script could determine what all sites are enabled by grabbing the file name after `sites-enabled/` and ignoring duplicate matches. And then it could simply lookup the files in the sites-available folder.

A little down the line, it might be good to have some kind of a2site command just for showing which sites are enabled and available. It looks like `httpd -M` is already good for displaying enabled mods, but perhaps showing enabled and disabled modules would be useful. But I have a feeling you were thinking about using `httpd -S` or `httpd -D DUMP_VHOSTS` to confirm that the vhost configurations are actually being recognized after the script moves them to the enabled directory. That's not a bad plan...

**Comment by enderandpeter** [comment]
So, for now the script is written in a way so that if you use the commands without parameters, it will return info about toggled mods and sites. `a2enmod` returns the output from `httpd -M` for enabled mods. For the disabled, it shows the names of modules in the main config file that are on commented-out LoadModule lines. `a2ensite` simply shows the output from `httpd -D DUMP_VHOSTS` for enabled sites and the list of files in `\conf\sites-available` for disabled sites.

Also I think I may understand the `httpd -D DUMP_VHOSTS` output a little more. The `default server` line shows the hostname by which the server is expecting clients to refer to it, as defined in the vhost block in the conf file it names. The remaining lines show that it's a named vhost in that the vhost block is looking for the servername the client specifies regardless of the IP address, provided port 80 is used. Although I'm still not sure why it displays that part twice.

I'll close this issue for the time being, but please let me know what other features you think would be useful or other information about mods and sites this utility should show.
